### ISSUE TITLE
Consider to restrict master to not allow push without PR

### ISSUE THREAD

**Issue by tourdownunder** [adventuresin/meetup_chatapp#9]
See [enabling-branch-restrictions](https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions)

**Comment by nickmeinhold** [comment]
Thanks for this, after we added the branch rule today, I tested pushing straight to master and got an error so I think it's setup as we intended.  

So for anyone reading this that's not clear, we're using the [feature branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow).

Also, PRs require 1 code review before they can be merged (and then anyone can merge).  

Great to have this sorted, thanks @tourdownunder!

**Comment by tourdownunder** [comment]
@nickmeinhold added the branch rule this issue can be closed.
